services:
  postgres_db:
    image: postgres:16-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: sigmasamitra
      POSTGRES_PASSWORD: sigmasamitra12
      POSTGRES_DB: sigmasamitraDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Pastikan port ini bebas di host Anda
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
